# Numpy

---

## Contents

- [Array di costanti numeriche](#constants)
- [Il _range_ di Numpy (*arange*)](#arange)
- [Divisione di un range in parti uguali (*linspace*)](#linspace)
- [Valori estratti da una distro uniforme in [0, 1]](#uniform)
- [Valori estratti da una distro normale](#normal)
- [Valori estratti random da un intervallo](#randint)
- [Cambiare le dimensioni con *reshape*](#reshape)
- [Concatenazione array in orizzontale o verticale](#concatenate)
- [Ordinare un array](#sort)
- [Condizioni logiche sull'array (*all* ed *any*)](#all-any)
- [Calcolo dei percentili](#percentile)
- [Calcolo di una descrittiva per righe o per colonne](#row-col-agg)
- [Attributi fondamentali di un array](#attribs)
- [Forzare il cast con *dtype*](#dtype)
- [Propagazione delle modifiche o creazione di una copia](#copy)

---

## Import

In [1]:
import numpy as np

---

<a id="constants"></a>
# Array di costanti numeriche

In [2]:
# Senza shape come tupla si ottiene una sola riga
# Sarebbe uguale a "shape = (5, )"

np.zeros(shape = 5, dtype = "int")

array([0, 0, 0, 0, 0])

In [3]:
# Anche se indico una sola riga in shape
# Ottengo comunque una matrice

np.zeros(shape = (1, 5), dtype = "int")

array([[0, 0, 0, 0, 0]])

In [4]:
# Vettore colonna!

np.zeros(shape = (5, 1), dtype = "int")

array([[0],
       [0],
       [0],
       [0],
       [0]])

In [5]:
# Matrice 2x4!

np.zeros(shape = (2, 4), dtype = "int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [6]:
# Con zeros_like posso creare una matrice identica a quella indicata ma contenente solo zeri!

x = np.array([[1, 2, 3], [4, 5, 6]])

np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
# Stesso discorso per per "ones"

np.ones(shape = 5, dtype = "int")

array([1, 1, 1, 1, 1])

In [8]:
# Stesso discorso per "full"

np.full(shape = 5, fill_value = 99, dtype = "float")

array([99., 99., 99., 99., 99.])

In [9]:
# Matrice identità!

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---

<a id="arange"></a>
# Il _range_ di Numpy (*arange*)

In [10]:
# Il valore di "stop" non è mai incluso

np.arange(start = 0, stop = 10, step = 1, dtype = "int")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# Invertire start e stop per avere l'array invertito non basta

np.arange(start = 10, stop = 0, step = 1)

array([], dtype=int32)

In [12]:
# Bisogna usare step negativo!

np.arange(start = 10, stop = 0, step = -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [13]:
# Funziona anche con step float!

np.arange(start = 0, stop = 1, step = 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---

<a id="linspace"></a>
# Divisione di un range in parti uguali (*linspace*)

In [14]:
# Caso semplice

np.linspace(start = 0, stop = 5, num = 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [15]:
# E' possibile anche ottenere un array invertito

np.linspace(start = 5, stop = 0, num = 5)

array([5.  , 3.75, 2.5 , 1.25, 0.  ])

---

<a id="uniform"></a>
# Valori estratti da una distro uniforme in [0,1]

In [16]:
# Con size singola è un vettore riga

np.random.random(size = 5)

array([0.63665738, 0.63810048, 0.73698514, 0.73075063, 0.59768461])

In [17]:
# Vettore colonna!

np.random.random(size = (5, 1))

array([[0.0465285 ],
       [0.22899592],
       [0.71146623],
       [0.57160972],
       [0.27620701]])

In [18]:
# Matrice!

np.random.random(size = (3, 3))

array([[0.05861771, 0.3426995 , 0.03936367],
       [0.20140657, 0.66986412, 0.81507252],
       [0.24231715, 0.02600313, 0.38606269]])

---

<a id="normal"></a>
# Valori estratti da una distro normale

In [19]:
# Media zero, deviazione standard uno

np.random.normal(loc = 0, scale = 1, size = 5)

array([-0.86070038, -0.15317876,  1.63590929, -1.7289985 , -0.19185808])

In [20]:
# Matrice 3x3 con valori estratti da una distribuzione normale
# Con media 3 e deviazione standard 2

np.random.normal(loc = 3, scale = 2, size = (3, 3))

array([[4.7415626 , 2.82192763, 3.05116024],
       [4.76149757, 5.74327317, 1.00027512],
       [7.35770605, 4.69583125, 4.70390572]])

In [21]:
# C'è anche randn che estrae direttamente dalla standard normal!
# Non ha parametri espliciti, si passsa solo il numero di dimensioni

np.random.randn(3, 3)

array([[ 1.11122817,  0.06371339, -1.44127798],
       [ 1.64997245, -1.30125184,  0.56263658],
       [-1.02622414,  1.440535  ,  0.99711291]])

---

<a id="randint"></a>
# Valori estratti random da un intervallo

In [22]:
# Il valore low può essere estratto, il valore high no

np.random.randint(low = 0, high = 10, size = 5)

array([2, 3, 7, 6, 0])

In [23]:
# Matrice di interi estratti random da [-5, 6)

np.random.randint(low = -5, high = 6, size = (3, 3))

array([[ 0,  4,  5],
       [-2, -4, -2],
       [ 5,  3,  1]])

---

<a id="reshape"></a>
# Cambiare le dimensioni con *reshape*

In [24]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
# Trasformazione in matrice quadrata, se possibile

x.reshape(int(np.sqrt(x.size)), int(np.sqrt(x.size)))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
# Stesso risultato di...

x.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [27]:
# Trasformazione in vettore colonna

x.reshape(x.size, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

---

<a id="concatenate"></a>
# Concatenazione array in orizzontale o verticale

In [28]:
x = np.array([10, 20, 30])
y = np.array([45, 46, 47])
m = np.arange(9).reshape(3, 3)

In [29]:
# Unione orizzontale

np.hstack([x, y])

array([10, 20, 30, 45, 46, 47])

In [30]:
# Unione verticale
# Due vettori riga diventano una matrice a due righe

np.vstack([x, y])

array([[10, 20, 30],
       [45, 46, 47]])

In [31]:
# Unione verticale fra un vettore riga e una matrice
# Da notare l'ordine degli elementi nel risultato

np.vstack([x, m])

array([[10, 20, 30],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

---

<a id="sort"></a>
# Ordinare un array

In [32]:
x = np.array([2, 1, 4, 3, 5])
x

array([2, 1, 4, 3, 5])

In [33]:
# Non in-place, bisognerebbe ri-assegnarlo

np.sort(x)

array([1, 2, 3, 4, 5])

In [34]:
# In-place!

x.sort()
x

array([1, 2, 3, 4, 5])

---

<a id="all-any"></a>
# Condizioni logiche sull'array (*all* ed *any*)

In [35]:
x = np.random.random(size = 100)
x

array([0.1418917 , 0.40861177, 0.88016773, 0.59850688, 0.05414073,
       0.47466536, 0.87380423, 0.25374305, 0.16177605, 0.68674884,
       0.16247652, 0.82260861, 0.21200752, 0.12812482, 0.45603662,
       0.6020365 , 0.08477978, 0.85516057, 0.54349032, 0.8297467 ,
       0.9232658 , 0.57786706, 0.46010175, 0.83777336, 0.34165241,
       0.75136446, 0.90978836, 0.09997009, 0.10707046, 0.33601641,
       0.11252984, 0.86566017, 0.68804148, 0.75527981, 0.77100026,
       0.66941468, 0.10216713, 0.57379076, 0.4066515 , 0.62263176,
       0.08598931, 0.66485247, 0.95129108, 0.61316681, 0.3446469 ,
       0.04341558, 0.96161993, 0.11069521, 0.73907262, 0.56083775,
       0.36420787, 0.96568277, 0.17423468, 0.58007248, 0.02437941,
       0.14946946, 0.8336558 , 0.84726528, 0.97641953, 0.7560721 ,
       0.65966796, 0.61967398, 0.0101972 , 0.54352765, 0.76582384,
       0.89959262, 0.03427519, 0.657343  , 0.52172736, 0.63666834,
       0.75969872, 0.73553372, 0.55824353, 0.94145167, 0.19338

In [36]:
# I numeri estratti sono tutti maggiori di 0.01 o è stato estratto qualche numero più piccolo?

np.all(x > 0.01)

True

In [37]:
# Ci sono dei numeri compresi fra 0.9 e 0.95?

np.any(~((x < 0.9) | (x > 0.95)))

True

---

<a id="percentile"></a>
# Calcolo dei percentili

In [38]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
# Per me 'nearest' è la migliore interpolazione
# Da notare come il percentile vada espresso da 0 a 100

np.percentile(a = x, q = 90, interpolation = "nearest")

8

---

<a id="row-col-agg"></a>
# Calcolo di una descrittiva per righe o per colonne

In [40]:
m = np.arange(9).reshape(3, 3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
# Il processo è applicabile con tutte le funzioni di aggregazione!

# I valori di axis possono confondere:
# Si tratta della dimensione che sarà collassata in fase di calcolo dell'aggregazione.
# Se axis = 0 sto collassando le righe, quindi voglio trovare la media di ogni colonna
# Se axis = 1 sto collassando le colonne, quindi voglio trovare la media di ogni riga

np.mean(m, axis = 0), np.mean(m, axis = 1)

(array([3., 4., 5.]), array([1., 4., 7.]))

In [42]:
# La media di ogni riga

m = np.random.randint(low = 0, high = 20, size = 9).reshape(3, 3)
print(m)

for row in range(0, m.shape[0]):
    print(f"La media di {m[row, :]} è {np.mean(m[row, :])}")

[[18  8  8]
 [12 12  0]
 [ 2 19 14]]
La media di [18  8  8] è 11.333333333333334
La media di [12 12  0] è 8.0
La media di [ 2 19 14] è 11.666666666666666


In [43]:
# La media di ogni colonna

m = np.random.randint(low = 0, high = 20, size = 9).reshape(3, 3)
print(m)

for col in range(0, m.shape[1]):
    print(f"La media di {m[:, col]} è {np.mean(m[:, col])}")

[[14 10  1]
 [18  8  2]
 [ 5  0  8]]
La media di [14 18  5] è 12.333333333333334
La media di [10  8  0] è 6.0
La media di [1 2 8] è 3.6666666666666665


---

<a id="attribs"></a>
# Attributi fondamentali di un array

In [44]:
x = np.random.random(size = (2, 3, 4))
x

array([[[0.48159714, 0.06604349, 0.30704867, 0.96068417],
        [0.79458352, 0.71116388, 0.08198471, 0.20760648],
        [0.3967711 , 0.3191711 , 0.92353105, 0.26254285]],

       [[0.93945449, 0.22100482, 0.36428245, 0.36711087],
        [0.51466912, 0.4035913 , 0.48811746, 0.60304453],
        [0.07133462, 0.60233366, 0.53318836, 0.40032448]]])

In [45]:
# Quante dimensioni ha l'array?

x.ndim

3

In [46]:
# Restituisce la lunghezza delle dimensioni dell'array.
# E' come se fossero 2 matrici 3x4.

x.shape

(2, 3, 4)

In [47]:
# Numero totale di elementi contenuti nella matrice.

x.size

24

---

<a id="dtype"></a>
# Forzare il cast con dtype

In [48]:
np.array([1, 2, 3, 4], dtype = "float")

array([1., 2., 3., 4.])

In [49]:
np.array([1.2, 2.5, 3.1, 4.9], dtype = "int")

array([1, 2, 3, 4])

In [50]:
np.array([1, 0, 1, 0], dtype = "bool")

array([ True, False,  True, False])

---

<a id="copy"></a>
# Propagazione delle modifiche o creazione di una copia

In [51]:
x = np.arange(16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [52]:
# Prendo le prime due righe e le prime due colonne

y = x[:2, :2]
y

array([[0, 1],
       [4, 5]])

In [53]:
# Modifico un elemento dell'array estratto

y[0, 1] = 99
y

array([[ 0, 99],
       [ 4,  5]])

In [54]:
# La modifica è avvenuta anche sull'array originale!

x

array([[ 0, 99,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
# Usando "copy" questo non accade

y = x[:2, :2].copy()
y[0, 0] = 888
x

array([[ 0, 99,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

---